### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by alexanderek** [zevilz/zabbix-alertscript-telegram#1]
Hello

When executing the script in the docker container, I get a message: The script only for using on GNU Linux dists!

The official zabbix [image](https://hub.docker.com/r/zabbix/zabbix-server-pgsql) is based on alpine linux.

**Comment by zevilz** [comment]
The script check `OSTYPE` var in OS. It throw this error if in `OSTYPE` not `linux-gnu`. But alpine linux have right value:
```
# docker exec zabbix-server-pgsql echo "$OSTYPE"
linux-gnu
```

**Comment by alexanderek** [comment]
zabbix/zabbix-server-pgsql:alpine-6.0-latest

```
bash-5.1$ echo "$OSTYPE"
linux-musl
```

I have now commented out this check in the script.

**Comment by seventhsite** [comment]
@alexanderek how you run script inside container? My zabbix-server-mysql:ubuntu-latest don't have inside: curl, jq, jo.

**Comment by alexanderek** [comment]
@seventhsite 

You need to make your Dockerfile

In my case, it's like this
```
FROM zabbix/zabbix-server-pgsql:alpine-6.0.14

USER root

RUN apk add --no-cache file curl jq jo && apk add --no-cache --upgrade grep

USER zabbix
```

further, if you use docker compose, you must specify build instead of image.
